---
- name: Update repositories cache and install docker dependencies
  tags:
    - docker_install
    - docker_update_depend  
  apt: name= "{{ item }}" state=latest update_cache=yes upgrade=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - gnupg
    - lsb-release

- name: Add docker repo apt key
  tags:
    - docker_install
    - docker_add_repo_key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_key_repo }}"
    state: present

- name: Add Docker Repository
  tags:
    - docker_install
    - docker_add_repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Update apt and install docker
  tags:
    - docker_install
    - docker_ce_install    
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start and enable systemd service docker
  tags:
    - docker_install
    - docker_start_service
    - docker_enable_service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  tags:
    - docker_install
    - add_users_to_docker_group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - ubuntu
    - ansible

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    state: link
