---
- name: Install Openldap + Rancher
  remote_user: ansible
  hosts: servers
  become: yes
  vars_files:
    - ./inventory/production/group_vars/servers.yml
  roles:
    - docker
    - openldap
    - rancher
