---
- name: Create a directories
  tags:
    - rancher_install
    - rancher_create_dir_proj
  file:
    path: "{{ PROJECT_DIR2 }}/{{ item }}"
    state: directory
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    recurse: yes
    mode: 0755
  with_items:
  - rancher

- name: Create docker-compose.yml file 
  tags:
    - rancher_install
    - rancher_create_docker_compose
  file:
    path: "{{ PROJECT_DIR2 }}/docker-compose.yml"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    state: touch 

- name: Deploy Docker Compose 
  tags:
    - rancher_install
    - rancher_deploy_docker_compose
  template:
    src: docker-compose.j2
    dest: "{{ PROJECT_DIR2 }}/docker-compose.yml"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0644

- name: Run docker-compose
  tags:
    - rancher_install
    - rancher_run_docker_compose
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ PROJECT_DIR2 }}"

