docker_apt_key_repo: https://download.docker.com/linux/ubuntu/gpg
docker_apt_repository: deb https://download.docker.com/linux/ubuntu focal stable
SERVER_IP: 192.168.0.109
SYSTEM_USER: ansible
PROJECT_DIR: /home/{{ SYSTEM_USER }}/openldap
PROJECT_DIR2: /home/{{ SYSTEM_USER }}/rancher
